version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PYTHONUNBUFFERED=1
